### ISSUE TITLE
0.28 Unable to select a time during another event

### ISSUE THREAD

**Issue by kyleabens** [mattlewis92/angular-calendar#1083]
**Describe the bug**
The time slots on the left hand side on the day view are no longer clickable. This is an issue for me because If I want to schedule an event which is set to begin at the same time as another event, I am unable to click a time since the existing event takes up the width of that day.

- `@angular/core`: 8.2.1
- `angular-calendar`: 0.28.0-beta.3
- Browser name and version: Google Chrome Version 76.0.3809.132

**Comment by mattlewis92** [comment]
Thanks! 👍

**Comment by kyleabens** [comment]
@mattlewis92 Not to be a pain but do you have an idea of when this fix would be available?

**Comment by mattlewis92** [comment]
I'll try and find some time this weekend, or you can use an older beta version for now, `beta.1` i think has date-fns v2, but not the day and week view merging

**Comment by mattlewis92** [comment]
Should be fixed now in `0.28.0-beta.4` 😄

**Comment by kyleabens** [comment]
Works great @mattlewis92 Thank you!

**Comment by fzs1994** [comment]
This is still an issue in v0.31.0: https://stackblitz.com/edit/angular-vymazu?file=src/app/app.component.ts
