### ISSUE TITLE
Angular 10 - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by JaxonWright** [mattlewis92/angular-calendar#1289]
**Describe the bug**

After trying to update to Angular 10, I get what I *think* is an error related to Angular Calendar or at least the accompanied date_fns library. Whenever I try to run `ng serve`, I get an `ERROR RangeError: Maximum call stack size exceeded` error and my project basically stops loading altogether.

**Screenshots**

![image](https://user-images.githubusercontent.com/14099593/85784054-e137e180-b6f5-11ea-9a39-35780da0395a.png)

**Versions**

- `@angular/core`: 10.0.0
- `angular-calendar`: 0.28.16
- Browser name and version: Chrome 83

**Comment by mattlewis92** [comment]
hmm weird, I know that there is a bug with 10.0.0 of the cli that completely breaks this library: https://github.com/mattlewis92/angular-calendar/issues/1285 but the error message is different from this one, although I _think_ it's the same issue. Can you try with `10.0.1` of the cli when it's released next week as I think it should be fixed then when this PR is released: https://github.com/angular/angular-cli/pull/18009

**Comment by salimchemes** [comment]
same here with both versions, 9 and 10

```
zone-evergreen.js:171 Uncaught RangeError: Maximum call stack size exceeded
    at Module.__assign (tslib.es6.js:1)
    at Object.adapterFactory (index.js:17)
    at Object.adapterFactory (index.js:17)
    at Object.adapterFactory (index.js:17)
    at Object.adapterFactory (index.js:17)
    at Object.adapterFactory (index.js:17)
    at Object.adapterFactory (index.js:17)
    at Object.adapterFactory (index.js:17)
    at Object.adapterFactory (index.js:17)
    at Object.adapterFactory (index.js:17)
```

**Comment by andyshear** [comment]
I can verify this is still happening in angular 10.0.2, as it did in 10.0.0 and 10.0.1

Going to try removing date-fns completely.  Calendar seems to be the only thing that broke updating from 8 -> 10 for my app.

core.js:4081 ERROR Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at Module.__assign (tslib.es6.js:1)
    at Object.adapterFactory (index.ts:18)
    at Object.adapterFactory (index.ts:19).........

**Comment by mattlewis92** [comment]
@andyshear The issue is with the @angular/cli not with @angular/core, the fix still hasn't been released in the cli (it's still on version 10.0.0): https://www.npmjs.com/package/@angular/cli

**Comment by ritxweb** [comment]
Fixed on Angular Cli 10.0.1
Thanks Matt for your job!! :)

**Comment by mattlewis92** [comment]
That is fantastic news, thanks for letting me know @ritxweb!

**Comment by pisix** [comment]
Despite the new version of angular/cli error is still happening 
`Angular CLI: 10.0.1
Node: 10.16.0
OS: darwin x64
`

**Comment by JaxonWright** [comment]
@pisix it doesn't happen for me anymore. Try updating your nodejs to the latest version, 14.4

**Comment by pisix** [comment]
Thanks @JaxonWright everything is ok now after updating nodejs to the latest version

**Comment by fravezzimattia** [comment]
Same errors with all different version of Angular/CLI >= 10.0.0.

Now my env is:

Angular CLI: 10.1.0-next.0
Node: 14.5.0
OS: win32 x64
Angular: 10.0.3

**Comment by pawelszymanski** [comment]
I had similar error. The problem was I was using a component with class selector (`selector: '.component-class',`) and both: parent compoment and this component had the class in the view:

```
// parent:
<div class=".component-class"></div>

// child
<div class=".component-class">
  ...
</div>

```

The obvious solution is not to have a wrapper in the child component, jsut the contents.

**Comment by YisalKhan** [comment]
> @pisix it doesn't happen for me anymore. Try updating your nodejs to the latest version, 14.4

I updated my node version to latest version, but the issue still exist.

**Comment by sanuKhanTpc** [comment]
Deleted **node_modules** and ran `npm install ` this worked for me! if anyone is still facing the issue  you can find my `ng version` below
`Angular CLI: 10.1.0
Node: 14.16.0
OS: win32 x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router   
... service-worker
Ivy Workspace: Yes`

**Comment by Hasan-git** [comment]
try :
npm cache clean --force
