### ISSUE TITLE
Request : Touch events

### ISSUE THREAD

**Issue by PierreDugue** [mattlewis92/angular-calendar#165]
### Bug description / Feature request:
Hello,

do you plan to add touch events, for a mobile utilisation? (For an utilisation on Ipad, or tablets for exemple)

Thx for your answere.

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
Sure I can take a look at this, what bits specifically aren't working with touch events? I believe if you include something like fast click: https://www.npmjs.com/package/fastclick it should get you most of the way there.

**Comment by PierreDugue** [comment]
Hello,

Thx for your answere. Is there an option I missed to activate the drag and drop on mobile browsers? I tried on my android phone and on an Ipad but the drag and drop is not working. That was actually my question, I forgot to specify I was talking about the drag an drop feature, sorry.

Thx for your help.

**Comment by mattlewis92** [comment]
Ah looks like I forgot to support touch events in the draggable lib, it should be fixed now in 0.9.1 😄

**Comment by svolga** [comment]
Hello, 

This bug still exists in mobile devices, in iPad. Have to switch off draggable property in event.
