### ISSUE TITLE
Refreshing view triggers beforeViewRender twice

### ISSUE THREAD

**Issue by mustafahlvc** [mattlewis92/angular-calendar#293]
## I'm submitting a ...

<pre>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Refreshing the view manually triggers the beforeViewRender event twice.

### Minimal reproduction of the problem with instructions

I just added console log on the plnkr with related refresh/re-render.
http://plnkr.co/edit/Gdp94MUAcJmHwIxco9mP?p=preview

### Versions

Angular: 4.3

Calendar library: ^0.19.0

Browser name and version:  Chrome 59..

**Thanks for the awesome component.**

**Comment by mattlewis92** [comment]
Thanks for reporting, this is now fixed in `0.20.0` 😄

**Comment by rafaelmenta** [comment]
Hi, I'm not sure if this is related but I'm still getting beforeViewRender being called twice when using directives form CalendarCommonModule.

First EventEmmiter has the current period and second has the period I'm moving the view to.
I didn't observe this issue on on Day/Month/Week modules (only 1 call) 

Added a console.warn to the event handler illustrating the issue: https://angular-g7uy4j.stackblitz.io

**Comment by syedfathima** [comment]
The beforeViewRender function triggers thrice  when click on date and view refresh .This issue still exist.How can we solve this?

**Comment by sebfie** [comment]
Same issue here

**Comment by pgarzina** [comment]
any follow up on this one?

**Comment by misgana96** [comment]
Do you have any solution to this one?
