### ISSUE TITLE
NullInjectorError: No provider for ElementRef!

### ISSUE THREAD

**Issue by sherkhanz** [mattlewis92/angular-calendar#588]
**Describe the bug**
Hi, Orignally I was gonna post about another bug but as the requirement for issue to be considered is a reproducible copy of code on slackblitz and slackblitz example code is giving me the above error when I try to run Custom Template code there. 
 
**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-hyehrq
Forked from here without any modifications: 
https://mattlewis92.github.io/angular-calendar/#/custom-templates

**Screenshots**
![sketch 9](https://user-images.githubusercontent.com/6374851/41204407-f43d0cf0-6c98-11e8-8657-95dd001cf124.png)

**Versions:**

 - `@angular/core`: 6.0.1
 - `angular-calendar` 0.25.2
 - Browser name and version: Chrome Latest

**Comment by mattlewis92** [comment]
Thanks for reporting, that's super weird. I've just pushed up a fix, please let me know if it works for you (you may have to clear your browser cache and reload the page for it to load up)

**Comment by teodoramalec** [comment]
Hi, does this error persists? Because I'm trying this demo for calendar and I get the same issues on stackblitz.

Versions: 

- @angular/cdk 5.1.1

- angular-calendar 0.24.1

![ccc](https://user-images.githubusercontent.com/23343764/42498831-ead448a4-8435-11e8-946e-6d23164e14ce.PNG)
