### ISSUE TITLE
Date of weekview is not updated, when weekStartsOn is not sunday

### ISSUE THREAD

**Issue by duck74** [mattlewis92/angular-calendar#868]
**Describe the bug**
When I update the weekStartsOn to a different day, in the week view the date in the header is still showing the days from Sunday to Saturday

**Minimal reproduction of the problem with instructions**
you can also see it here in the examples:
https://mattlewis92.github.io/angular-calendar/#/i18n

Here the week starts on Monday but the date in the header still is the Sunday date

**Screenshots**

**Versions**

- `@angular/core`:
Angular CLI: 7.0.3
Node: 11.3.0
OS: darwin x64
Angular: 6.1.4
- `angular-calendar`: "angular-calendar": "^0.26.4"
- Browser name and version: Mac OS: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by Jab0rnal** [comment]
Ah, I've just come across this. Id hoped that i was doing something wrong. Any news on a fix?

**Comment by mattlewis92** [comment]
Fixed in `0.26.8`! 😄

**Comment by Kherat** [comment]
"angular-calendar": "^0.26.11",
But is not fixed and local cuz error in publish

**Comment by duck74** [comment]
Kherat is right, it did not work when I tried it, I came up with a workaround, but will try it again

**Comment by Kherat** [comment]
waiting for a good solution...

**Comment by mattlewis92** [comment]
<img width="1131" alt="Screenshot 2019-04-17 at 18 32 50" src="https://user-images.githubusercontent.com/6425649/56281464-3e71f380-613f-11e9-9940-b2b4be9c6819.png">
It's working for me, can someone make a repro on stackblitz?

**Comment by Kherat** [comment]
![22](https://user-images.githubusercontent.com/47124139/56282581-26d34480-6118-11e9-8128-500d996995f8.png)

**Comment by duck74** [comment]
Just checked my app and its now on version 0.27.3 but still shows the same error.
this is my calendar header component entry:
  
      <h3> {{ viewDate | calendarDate:(view + 'ViewTitle'):locale }}</h3>
  I have the German locale.
<img width="824" alt="Screen Shot 2019-04-17 at 13 12 26" src="https://user-images.githubusercontent.com/4760249/56283707-cab9f180-6112-11e9-8612-31d8632c827f.png">

**Comment by mattlewis92** [comment]
Ahh I see now, so you need to pass the `weekStartsOn` to the header pipe and it'll solve your problem 😄 
```
{{ viewDate | calendarDate:(view + 'ViewTitle'):locale:weekStartsOn }}
```

**Comment by duck74** [comment]
OK thanks, it is working now (I also had to add the Input in the header component as well as to adapt the calendar-header in the html of the calendar component (just in case someone else is having the same problem :) )
Thanks a lot for the help!

**Comment by Kherat** [comment]
when I add this line 
{{ viewDate | calendarDate:(view + 'ViewTitle'):locale:weekStartsOn }}
i got error about local while publishing project.
