### ISSUE TITLE
Can't drag event on last day of week view

### ISSUE THREAD

**Issue by jcjobin** [mattlewis92/angular-calendar#871]
**Describe the bug**
Currently I find that I cannot drag or resize an event on the last day of a week view. 
This can be replicated on the demo site by changing a couple elements: https://mattlewis92.github.io/angular-calendar/#/draggable-events

This occurs in Chrome only. The dragging still works if you zoom the window to 90% or 110%. The window needs to be maximized. 

**Minimal reproduction of the problem with instructions**
Within inspect element, you need to set the calendar div from col-md-9 to col-md-12 (to make it full screen) and remove left and right padding from the col-md-12 class. If you drag the event to saturday, then you cannot drag the event within saturday. But you can drag it to another day of the week.

I will try to create a plunkr to replicate this simply, that will later be added as an edit.

**Versions**
Most recent version of Angular and Angular Calendar

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:
Google Chrome v 72.0.3626.81 64bit

**Comment by jcjobin** [comment]
A fix here would be to add padding-left and padding-right to the parent element. I feel that this bug should still be known though.

**Comment by mattlewis92** [comment]
Hi there! I tried to reproduce your issue by following the steps you posted but was unable to, would you mind adding a stackblitz that reproduces your issue? You can fork one from any of the demos by hitting the edit with stackblitz button

![kapture 2019-02-05 at 15 34 03](https://user-images.githubusercontent.com/6425649/52261298-8d3f2800-295b-11e9-8c88-75cb3c2e159e.gif)

Thanks! 👍

**Comment by jcjobin** [comment]
> Hi there! I tried to reproduce your issue by following the steps you posted but was unable to, would you mind adding a stackblitz that reproduces your issue? You can fork one from any of the demos by hitting the edit with stackblitz button
> 
> ![kapture 2019-02-05 at 15 34 03](https://user-images.githubusercontent.com/6425649/52261298-8d3f2800-295b-11e9-8c88-75cb3c2e159e.gif)
> 
> Thanks! 👍

Thanks for the reply! I actually just went to the stackblitz (thank you for that). And I was able to replicate it within the stackblitz. What I noticed in your video is it looks like there is padding on the right (between the calendar and scroll bar). In my video, when I first go to the week view there is no space and it won't drag. But when I release, you can see a scroll bar appear and the site seems to re-size. Then the drag works. 
I am beginning to think it is a Chrome-related issue. But not sure how that would play into it.

Thanks
![unable_drag](https://user-images.githubusercontent.com/11465133/52271706-d458f900-291a-11e9-9e8b-4b39630619bc.gif)

**Comment by Rudy-vgs** [comment]
I'm having the same problem with the drag to create. Can not create an event on the last day of the week. Is there a fix (even temporary) ?

**Comment by jcjobin** [comment]
> I'm having the same problem with the drag to create. Can not create an event on the last day of the week. Is there a fix (even temporary) ?
> 
> The problem also appears on Mozilla

I found that adding padding around the calendar may or may not help. I was able to get it working at times, but it was still unpredictable. Seemed like Chrome was the only one with the issue though.

**Comment by jcjobin** [comment]
> I'm having the same problem with the drag to create. Can not create an event on the last day of the week. Is there a fix (even temporary) ?
> 
> The problem also appears on Mozilla

Also, try zooming out to 110% or zoom in to 90% (ctrl+zoom). I was also able to get it to work then, but that is not a solution for general users of the app.

**Comment by mattlewis92** [comment]
Should be fixed now in `0.26.10`, thanks for reporting! 😄

**Comment by sebmin** [comment]
Hi, 
Unfortunately, the problem still appears if I set [weekStartsOn] on different value than 0.  
My [weekStartsOn]="1" and I cannot drag event more than 15 minutes ([hourSegments]="4").
I assume that the issue is similar to the one which you solve recently.
